---
title: "Alignment"
format: html
editor: visual
---

## Testing Alignments output

```{r eval=FALSE}

library(gtsummary)
tbl <- gtsummary::tbl_summary(gtsummary::trial, by = trt, include = c(age, grade), missing = "always", label = list(age = "Age")) |> add_overall()

gt_table <- tbl$table_body |> 
  gt::gt(caption = gt::md("This is the caption  \n[Used for cross referencing in Quarto]")) |> 
  gt::cols_align(columns = c(stat_1, stat_2), align = "right") |> 
  gt::cols_align(columns = c(variable, var_type), align = "center") |>
  gt::cols_align(columns = c(row_type, var_label), align = "left")
```

### gt_save PDF

```{r eval = FALSE}
gt::gtsave(gt_table, filename = "outputs/pdf/alignment_gt_pdf.pdf")
```

[Preview the Output](outputs/pdf/alignment_gt_pdf.pdf)

-   no issues

### rmarkdown rendered PDF

```{r eval = FALSE}
gt_table
```

[Preview the Output](outputs/pdf/alignment_rmd_pdf.pdf)

-   no issues

### gt_save rendered word file

```{r eval = FALSE}
gt::gtsave(gt_table, filename = "outputs/docx/alignment_gt_word.docx")
```

[Preview the Output](outputs/docx/alignment_gt_word.docx)

-   no issues

### quarto rendered word file

```{r eval = FALSE}
gt_table
```

[Preview the Output](outputs/docx/alignment_qmd_word.docx)

-   no issues

### rmarkdown rendered word file

```{r eval = FALSE}
gt_table
```

[Preview the Output](outputs/docx/alignment_rmd_word.docx)

-   no issues
