---
title: "Text Styling"
format: html
editor: visual
---

## Testing Text Styling output

```{r eval=T}

library(gtsummary)
tbl <- gtsummary::tbl_summary(gtsummary::trial, by = trt, include = c(age, grade), missing = "always", label = list(age = "Age")) |> add_overall()

gt_table <- tbl$table_body |> 
  gt::gt(caption = gt::md("This is the caption  \n[Used for cross referencing in Quarto]")) |> 
 # Bold cells in table
  gt::tab_style(
    style = gt::cell_text(weight = "bold"), 
    locations = gt::cells_body(columns = "label", rows = c(1, 3))
  ) 

gt_table
```

### gt_save PDF

```{r eval = FALSE}
gt::gtsave(gt_table, filename = "outputs/pdf/bold_gt_pdf.pdf")
```

[Preview the Output](outputs/pdf/bold_gt_pdf.pdf)

-   no issues

### rmarkdown rendered PDF

```{r eval = FALSE}
gt_table
```

[Preview the Output](outputs/pdf/bold_rmd_pdf.pdf)

-   no issues

### gt_save rendered word file

```{r eval = FALSE}
gt::gtsave(gt_table, filename = "outputs/docx/bold_gt_word.docx")
```

[Preview the Output](outputs/docx/bold_gt_word.docx)

-   no issues

### quarto rendered word file

```{r eval = FALSE}
gt_table
```

[Preview the Output](outputs/docx/bold_qmd_word.docx)

-   no issues

### rmarkdown rendered word file

```{r eval = FALSE}
gt_table
```

[Preview the Output](outputs/docx/bold_rmd_word.docx)

-   no issues
