project:
  type: website
  render:
    - "*.qmd"
    - "!renderdocs/"
format:
  html:
    search: true
    anchor-sections: true
    smooth-scroll: true
    code-link: true
    code-fold: false
    code-overflow: scroll
    code-line-numbers: true
    code-copy: true
    code-tools:
      source: true
      toggle: false
      caption: none
    code-block-bg: true
    css: quarto/assets/style.scss
    toc: false
    number-sections: false
    lang: en-US
    page-layout: full
    df-print: kable

execute:
  freeze: auto
  cache: true
  code-line-numbers: true

knitr:
  opts_chunk:
    echo: true
    code-fold: show
    fig.width: 15

website:
  page-navigation: true
  title: "Table Drawing Research"
  description: "Table Engine output Experimentation"

  repo-url: https://github.com/insightsengineering/table.drawing.research
  repo-actions: [edit, issue]

  page-footer:
    background: "#B8D09F"

  sidebar:
    background: "#B8D09F"
    pinned: true
    align: center
    tools:
      - icon: github
        text: GitHub
    style: docked
    contents:
     - href: index.qmd
       text: Home
     - href: 01_line_breaks.qmd
       text: Line Breaks
     - href: 02_indentation.qmd
       text: Indentation
     - href: 03_spanning_header.qmd
       text: Spanning Header
     - href: 04_footnotes.qmd
       text: Footnotes
     - href: 05_source_notes.qmd
       text: Source Notes
     - href: 06_titles.qmd
       text: Titles
     - href: 07_alignment.qmd
       text: Alignment
     - href: 08_text_styling.qmd
       text: Text Styling
     - href: 09_tbl_too_long.qmd
       text: Table Too Long
     - href: 10_tbl_too_wide.qmd
       text: Table Too Wide
     - href: 11_other_engines.qmd
       text: Other Engines
editor: source
